export type GuideEntry = {
  id: string;
  name: string;
  description: string;
  group: "Foundations" | "Components";
  status?: "Stable" | "Draft";
};

export const foundationEntries: GuideEntry[] = [
  {
    id: "introduction",
    name: "Introduction",
    description: "Purpose and design posture",
    group: "Foundations",
  },
  {
    id: "principles",
    name: "Principles",
    description: "Rules behind the visual language",
    group: "Foundations",
  },
  {
    id: "colors",
    name: "Color",
    description: "Semantic color tokens",
    group: "Foundations",
  },
  {
    id: "typography",
    name: "Typography",
    description: "Editorial scale and technical detail",
    group: "Foundations",
  },
  {
    id: "spacing",
    name: "Spacing",
    description: "Rhythm, density, and alignment",
    group: "Foundations",
  },
];

export const componentEntries: GuideEntry[] = [
  {
    id: "accordion",
    name: "Accordion",
    description: "Reveal related content sections",
    group: "Components",
    status: "Stable",
  },
  {
    id: "alert",
    name: "Alert",
    description: "Communicate important state",
    group: "Components",
    status: "Stable",
  },
  {
    id: "avatar",
    name: "Avatar",
    description: "Represent a person or entity",
    group: "Components",
    status: "Stable",
  },
  {
    id: "badge",
    name: "Badge",
    description: "Label status or metadata",
    group: "Components",
    status: "Stable",
  },
  {
    id: "banner",
    name: "Banner",
    description: "Announce page-level information",
    group: "Components",
    status: "Stable",
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    description: "Show the current location",
    group: "Components",
    status: "Stable",
  },
  {
    id: "button",
    name: "Button",
    description: "Trigger an action",
    group: "Components",
    status: "Stable",
  },
  {
    id: "button-group",
    name: "Button Group",
    description: "Group related actions",
    group: "Components",
    status: "Stable",
  },
  {
    id: "card",
    name: "Card",
    description: "Group related information",
    group: "Components",
    status: "Stable",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    description: "Select one or more options",
    group: "Components",
    status: "Stable",
  },
  {
    id: "collapsible",
    name: "Collapsible",
    description: "Show or hide supporting content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "combobox",
    name: "Combobox",
    description: "Search and select an option",
    group: "Components",
    status: "Stable",
  },
  {
    id: "container",
    name: "Container",
    description: "Constrain page content width",
    group: "Components",
    status: "Stable",
  },
  {
    id: "date-picker",
    name: "Date Picker",
    description: "Select a calendar date",
    group: "Components",
    status: "Stable",
  },
  {
    id: "description-list",
    name: "Description List",
    description: "Pair terms with descriptions",
    group: "Components",
    status: "Stable",
  },
  {
    id: "dialog",
    name: "Dialog",
    description: "Focus a short task",
    group: "Components",
    status: "Stable",
  },
  {
    id: "divider",
    name: "Divider",
    description: "Separate related content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "drawer",
    name: "Drawer",
    description: "Open a task from the screen edge",
    group: "Components",
    status: "Stable",
  },
  {
    id: "empty-state",
    name: "Empty State",
    description: "Explain an area without content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "fieldset",
    name: "Fieldset",
    description: "Group related form controls",
    group: "Components",
    status: "Stable",
  },
  {
    id: "file-upload",
    name: "File Upload",
    description: "Select files for upload",
    group: "Components",
    status: "Stable",
  },
  {
    id: "form",
    name: "Form",
    description: "Collect and submit structured data",
    group: "Components",
    status: "Stable",
  },
  {
    id: "form-error-summary",
    name: "Form Error Summary",
    description: "Summarize validation problems",
    group: "Components",
    status: "Stable",
  },
  {
    id: "form-field",
    name: "Form Field",
    description: "Connect labels, controls, and help",
    group: "Components",
    status: "Stable",
  },
  {
    id: "form-section",
    name: "Form Section",
    description: "Organize related form fields",
    group: "Components",
    status: "Stable",
  },
  {
    id: "grid",
    name: "Grid",
    description: "Arrange content in columns",
    group: "Components",
    status: "Stable",
  },
  {
    id: "header",
    name: "Header",
    description: "Introduce a page or region",
    group: "Components",
    status: "Stable",
  },
  {
    id: "heading",
    name: "Heading",
    description: "Name a content section",
    group: "Components",
    status: "Stable",
  },
  {
    id: "icon",
    name: "Icon",
    description: "Display a symbolic visual",
    group: "Components",
    status: "Stable",
  },
  {
    id: "image",
    name: "Image",
    description: "Present responsive visual content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "input",
    name: "Input",
    description: "Collect a short value",
    group: "Components",
    status: "Stable",
  },
  {
    id: "input-group",
    name: "Input Group",
    description: "Combine an input with adjacent controls",
    group: "Components",
    status: "Stable",
  },
  {
    id: "link",
    name: "Link",
    description: "Navigate to another location",
    group: "Components",
    status: "Stable",
  },
  {
    id: "list",
    name: "List",
    description: "Present related items",
    group: "Components",
    status: "Stable",
  },
  {
    id: "main",
    name: "Main",
    description: "Identify the primary page content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "menu",
    name: "Menu",
    description: "Offer a compact set of actions",
    group: "Components",
    status: "Stable",
  },
  {
    id: "navigation-menu",
    name: "Navigation Menu",
    description: "Navigate between major destinations",
    group: "Components",
    status: "Stable",
  },
  {
    id: "number-input",
    name: "Number Input",
    description: "Collect a numeric value",
    group: "Components",
    status: "Stable",
  },
  {
    id: "page",
    name: "Page",
    description: "Compose a complete application page",
    group: "Components",
    status: "Stable",
  },
  {
    id: "page-header",
    name: "Page Header",
    description: "Introduce page context and actions",
    group: "Components",
    status: "Stable",
  },
  {
    id: "pagination",
    name: "Pagination",
    description: "Move through paged content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "popover",
    name: "Popover",
    description: "Show contextual interactive content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "progress",
    name: "Progress",
    description: "Show task completion",
    group: "Components",
    status: "Stable",
  },
  {
    id: "prose",
    name: "Prose",
    description: "Style long-form content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "radio-group",
    name: "Radio Group",
    description: "Choose one option from a set",
    group: "Components",
    status: "Stable",
  },
  {
    id: "select",
    name: "Select",
    description: "Choose an option from a list",
    group: "Components",
    status: "Stable",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    description: "Provide secondary navigation",
    group: "Components",
    status: "Stable",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    description: "Represent loading content",
    group: "Components",
    status: "Stable",
  },
  {
    id: "skip-link",
    name: "Skip Link",
    description: "Bypass repeated navigation",
    group: "Components",
    status: "Stable",
  },
  {
    id: "slider",
    name: "Slider",
    description: "Choose a value from a range",
    group: "Components",
    status: "Stable",
  },
  {
    id: "spinner",
    name: "Spinner",
    description: "Indicate indeterminate activity",
    group: "Components",
    status: "Stable",
  },
  {
    id: "stack",
    name: "Stack",
    description: "Arrange children with consistent space",
    group: "Components",
    status: "Stable",
  },
  {
    id: "stat",
    name: "Stat",
    description: "Highlight a key measurement",
    group: "Components",
    status: "Stable",
  },
  {
    id: "status-indicator",
    name: "Status Indicator",
    description: "Pair a state marker with a label",
    group: "Components",
    status: "Stable",
  },
  {
    id: "stepper",
    name: "Stepper",
    description: "Show progress through ordered steps",
    group: "Components",
    status: "Stable",
  },
  {
    id: "switch",
    name: "Switch",
    description: "Toggle an immediate setting",
    group: "Components",
    status: "Stable",
  },
  {
    id: "table",
    name: "Table",
    description: "Display structured tabular data",
    group: "Components",
    status: "Stable",
  },
  {
    id: "table-of-contents",
    name: "Table of Contents",
    description: "Navigate long-form sections",
    group: "Components",
    status: "Stable",
  },
  {
    id: "tabs",
    name: "Tabs",
    description: "Switch between related views",
    group: "Components",
    status: "Stable",
  },
  {
    id: "text",
    name: "Text",
    description: "Render semantic body text",
    group: "Components",
    status: "Stable",
  },
  {
    id: "textarea",
    name: "Textarea",
    description: "Collect longer text",
    group: "Components",
    status: "Stable",
  },
  {
    id: "time-picker",
    name: "Time Picker",
    description: "Select a time",
    group: "Components",
    status: "Stable",
  },
  {
    id: "toast",
    name: "Toast",
    description: "Report transient feedback",
    group: "Components",
    status: "Stable",
  },
  {
    id: "toggle",
    name: "Toggle",
    description: "Switch a pressed state",
    group: "Components",
    status: "Stable",
  },
  {
    id: "toggle-group",
    name: "Toggle Group",
    description: "Choose one or more pressed options",
    group: "Components",
    status: "Stable",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    description: "Describe an element on hover or focus",
    group: "Components",
    status: "Stable",
  },
];

export const guideEntries = [...foundationEntries, ...componentEntries];

export function isGuideEntry(id: string): boolean {
  return guideEntries.some((entry) => entry.id === id);
}
